spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/case
    username: case_user
    password: case1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-stacktrace: never